### ISSUE TITLE
Airplane example: Dragging airfoil scale causes snap change in wing taper

### ISSUE THREAD

**Issue by whoburg** [bqpd/cadtoon#1]
Here: http://bqpd.github.io/cadtoons/flightconditions.html

**Comment by bqpd** [comment]
Are you doing a wingtaper.scalex of greater than 1?

**Comment by whoburg** [comment]
Hmm, behavior has changed since ticket was submitted. Originally, when loading the page linked above, the wing showed up as a trapezoid (before adjusting any sliders). It then snapped to a triangle upon moving the airfoil.scale slider at all. Now, however, it shows up from the beginning as a triangle.

**Comment by whoburg** [comment]
This is on Safari version 7.1.2.

**Comment by bqpd** [comment]
Yup, because it now runs constraints on page load. This is expected. Does the slider work as expected between wingtaper.scalex=0 and 1?

**Comment by whoburg** [comment]
Starts with triangle - seems to be working as intended.
