### ISSUE TITLE
Ractive src update

### ISSUE THREAD

**Issue by pgk-vho** [bqpd/cadtoon#3]
Ran into an error that was solved by editing the `.html` as follows:

```
-  <script src='http://cdn.ractivejs.org/latest/ractive.min.js'></script>
+  <script src='https://cdn.jsdelivr.net/npm/ractive'></script>
```

**Comment by bqpd** [comment]
Great, pushed to master! (wondering if the js should just be included since I'm not sure ractive is still maintained...)
